name: core_backend
description: Core package for project's backend common code.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  core_common: 
    path: ../core_common
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  sqlite3: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
